export const Thematics = [
    {id: 1, name: "PS4"},
    {id: 2, name: "PS3"},
    {id: 3, name: "Xbox One"},
    {id: 4, name: "Switch"},
    {id: 5, name: "3DS"},
    {id: 6, name: "PC"},
    {id: 7, name: "Настолки"},
    {id: 8, name: "Сувениры"},
    {id: 9, name: "Комиксы"},
    {id: 10, name: "Другое"},
];

export const Games = [
    {
        id: 1,
        name: "Doom Eternal",
        description: "Цвет упаковки: Темно красный",
        image: "https://i.ytimg.com/vi/_9lobt5mtDE/hqdefault.jpg",
        price: 1999,
    },
    {
        id: 2,
        name: "Cyberpunk 2077",
        description: "Цвет упаковки: Черный и желтый",
        image: "https://www.gamepark.ru/upload/iblock/ba9/predzakaz_igry_cyberpunk_2077.jpg",
        price: 1999,
    },
    {
        id: 3,
        name: "Star Wars™ Battlefront™ II",
        description: "Цвет упаковки: Черный и синий",
        image: "https://media.contentapi.ea.com/content/dam/walrus/ru-ru/migrated-images/2017/04/reveal-swbf2-fb-meta-image-alt.png.adapt.crop191x100.1200w.png",
        price: 2499,
    },
    {
        id: 4,
        name: "Horizon Zero Dawn",
        description: "Цвет упаковки: Голубой и зеленый",
        image: "https://i1.wp.com/itc.ua/wp-content/uploads/2020/03/horizon-zero-dawn.jpg?fit=1920%2C1080&quality=100&strip=all&ssl=1",
        price: 1199,
    },
    {
        id: 5,
        name: "Ведьмак 3: Дикая Охота",
        description: "Цвет упаковки: Черный и серый",
        image: "https://droider.ru/wp-content/uploads/2020/05/9062b66b.jpeg",
        price: 1799,
    },
];
export const NewGames = [
    {
        id: 1,
        name: "Cyberpunk 2077",
        description: "Цвет упаковки: Черный и желтый",
        image: "https://www.gamepark.ru/upload/iblock/ba9/predzakaz_igry_cyberpunk_2077.jpg",
        price: 1999,
    },
    {
        id: 2,
        name: "Star Wars™ Battlefront™ II",
        description: "Цвет упаковки: Черный и синий",
        image: "https://media.contentapi.ea.com/content/dam/walrus/ru-ru/migrated-images/2017/04/reveal-swbf2-fb-meta-image-alt.png.adapt.crop191x100.1200w.png",
        price: 2499,
    },
    {
        id: 3,
        name: "Horizon Zero Dawn",
        description: "Цвет упаковки: Голубой и зеленый",
        image: "https://i1.wp.com/itc.ua/wp-content/uploads/2020/03/horizon-zero-dawn.jpg?fit=1920%2C1080&quality=100&strip=all&ssl=1",
        price: 1199,
    },
    {
        id: 4,
        name: "Ведьмак 3: Дикая Охота",
        description: "Цвет упаковки: Черный и серый",
        image: "https://droider.ru/wp-content/uploads/2020/05/9062b66b.jpeg",
        price: 1799,
    },
    {
        id: 5,
        name: "Cyberpunk 2077",
        description: "Цвет упаковки: Черный и желтый",
        image: "https://www.gamepark.ru/upload/iblock/ba9/predzakaz_igry_cyberpunk_2077.jpg",
        price: 1999,
    },
    {
        id: 6,
        name: "Star Wars™ Battlefront™ II",
        description: "Цвет упаковки: Черный и синий",
        image: "https://media.contentapi.ea.com/content/dam/walrus/ru-ru/migrated-images/2017/04/reveal-swbf2-fb-meta-image-alt.png.adapt.crop191x100.1200w.png",
        price: 2499,
    },
    {
        id: 7,
        name: "Horizon Zero Dawn",
        description: "Цвет упаковки: Голубой и зеленый",
        image: "https://i1.wp.com/itc.ua/wp-content/uploads/2020/03/horizon-zero-dawn.jpg?fit=1920%2C1080&quality=100&strip=all&ssl=1",
        price: 1199,
    },
    {
        id: 8,
        name: "Ведьмак 3: Дикая Охота",
        description: "Цвет упаковки: Черный и серый",
        image: "https://droider.ru/wp-content/uploads/2020/05/9062b66b.jpeg",
        price: 1799,
    },
];
